ApplicationName = 'Application name'
DebugInfo = false
EmitIntermiediateIR = true
FavourSize = false
IncludeCStandard = true
IncludeClearStandard = false
LibraryDirectories = [ 'Any library directories go here' ]
LibraryNames = [ 'Library names go here' ]
OptimizationLevel = 'Development'
OutputFilename = 'Output filename goes here'
OutputFormat = 'Executable'
OutputPath = 'Output path goes here'
ParallelBuild = false
SourceDirectories = [ 'Source directories go here' ]
SourceFiles = [ 'Source files go here' ]
StandardLibrary = 'Input standard library path here'
TargetArchitecture = 'Default'
TargetExtension = '.cl'
WarningLevel = 'Medium'

[CPUFeatures]
AVX = false
AVX2 = false
AVX512 = false
BMI1 = false
BMI2 = false
FMA = false
NEON = false
SSE = false
SSE2 = false
SSE3 = false
SSE4_1 = false
SSE4_2 = false
SSSE3 = false