#pragma once
namespace clear
{
	enum DiagnosticCode
	{
		DiagnosticCode_None,
		DiagnosticCode_InvalidSyntax,
		DiagnosticCode_DivisionByZero,
		DiagnosticCode_InvalidOperator,
		DiagnosticCode_UnterminatedComment,
		DiagnosticCode_UnterminatedString,
		DiagnosticCode_UnexpectedEOF,
		DiagnosticCode_InvalidNumberLiteral,
		DiagnosticCode_InvalidCharLiteral,
		DiagnosticCode_RedefinedIdentifier,
		DiagnosticCode_UndeclaredIdentifier,
		DiagnosticCode_TypeMismatch,
		DiagnosticCode_InvalidEscapeSequence,
		DiagnosticCode_UnmatchedBracket,
		DiagnosticCode_UnexpectedToken,
		DiagnosticCode_ExpectedIndentation,
		DiagnosticCode_ExpectedNewlineAferIndentation,
		DiagnosticCode_ExpectedIdentifier,
		DiagnosticCode_ExpectedAssignment,
		DiagnosticCode_ElseNotInIfBlock,
		DiagnosticCode_InvalidForLoop,
		DiagnosticCode_ExpectedLeftParanFunctionDefinition,
		DiagnosticCode_ExpectedEndOfFunction,
		DiagnosticCode_ExpectedCommaBetweenFunctionParams,
		DiagnosticCode_ExpectedFunctionReturnType,
		DiagnosticCode_ExpectedEndOfScope,
		DiagnosticCode_ExpectedModuleName,
		DiagnosticCode_ExpectedComma,
		DiagnosticCode_ExpectedColon,
		DiagnosticCode_NeedsTypeOrValue,
		DiagnosticCode_LoopControlOutsideLoop,
		DiagnosticCode_VariadicNotLast,
		DiagnosticCode_ImportNotFound,
		DiagnosticCode_InvalidArraySize,
		DiagnosticCode_InvalidMemberAccess,
		DiagnosticCode_UnknownMember,
		DiagnosticCode_MissingIndexOverload,
		DiagnosticCode_ExpectedType,
		DiagnosticCode_InvalidOperands,
		DiagnosticCode_ReturnTypeMismatch,
		DiagnosticCode_MissingReturnValue,
		DiagnosticCode_WrongArgumentCount,
		DiagnosticCode_ArgumentTypeMismatch,
		DiagnosticCode_NotCallable,
		DiagnosticCode_AssignToRValue,
		DiagnosticCode_DuplicateCase,
		DiagnosticCode_NonConstantCase,
		DiagnosticCode_CannotInferGeneric,
		DiagnosticCode_ImplicitConversion,
		DiagnosticCode_NotIterable,
		DiagnosticCode_ExpectedCase,
		DiagnosticCode_ConstNeedsValue,
		DiagnosticCode_AssignToConst,
		DiagnosticCode_InvalidEnumValue,
		DiagnosticCode_DeferOutsideFunction,
		DiagnosticCode_SwitchNotIntegral,
		DiagnosticCode_MissingOperatorOverload,
		DiagnosticCode_BadOperatorSignature,
		DiagnosticCode_TooManyValues,
		DiagnosticCode_GenericMethodUnsupported,
		DiagnosticCode_IndexNotInteger,
		DiagnosticCode_NoLength,
		DiagnosticCode_IndexOutOfRange,
		DiagnosticCode_NullDereference,
		DiagnosticCode_ShiftOutOfRange,
		DiagnosticCode_LiteralOutOfRange,
		DiagnosticCode_MissingReturn,
		Diagnostic_Count
	};
	inline const char* g_DiagnosticMessages[] = {
		"An unknown error has occurred.",
		"Syntax error: unexpected or invalid token.",
		"Division by zero is undefined.",
		"Invalid or unsupported operator used.",
		"Unterminated block comment detected.",
		"Unterminated string literal.",
		"Unexpected end of file.",
		"Invalid numeric literal.",
		"Invalid character literal.",
		"Redefinition of identifier.",
		"Use of undeclared identifier.",
		"Type mismatch in assignment or operation.",
		"Invalid escape sequence in string literal.",
		"Unmatched closing or opening bracket.",
		"Unexpected token encountered.",
		"Expected ':' for block indentation",
		"Expected a new line after ':'",
		"Expected an identifier",
		"Expected '=' after identifier",
		"Unexpected 'else' without matching 'if'",
		"Invalid 'for' loop.",
		"Expected '(' after function name",
		"Expected ')' at end of parameter list",
		"Expected ',' between function parameters",
		"Missing '->' for function return type",
		"Expected end of scope (e.g. end of class or function block)",
		"Expected a module name string",
		"Expected ',' between list or argument elements.",
		"Expected ':' after case label or block starter.",
		"A variable needs a type or an initial value.",
		"‘break’ or ‘continue’ used outside of a loop.",
		"Variadic parameter must be the last parameter.",
		"Imported file could not be found.",
		"Array size must be a positive compile-time constant.",
		"Invalid member access.",
		"Type has no member with this name.",
		"Type cannot be indexed.",
		"Expected a type.",
		"Operator cannot be applied to these operand types.",
		"Returned value does not match the function's return type.",
		"Function must return a value.",
		"Wrong number of arguments in function call.",
		"Argument type does not match the parameter type.",
		"Expression is not callable.",
		"Cannot assign to this expression.",
		"Duplicate case value in switch.",
		"Case values must be integer constants.",
		"Cannot infer the type arguments of a generic type.",
		"Cannot convert implicitly, the conversion may lose information.",
		"Value cannot be iterated over.",
		"Expected ‘case’ or ‘default’ inside a switch.",
		"A constant needs a value.",
		"Cannot change a constant.",
		"Enum values must be integer constants.",
		"‘defer’ can only be used inside a function.",
		"Switch value must be an integer or an enum.",
		"Operator is not defined for this class.",
		"Operator method has the wrong number of parameters.",
		"Too many values for this class.",
		"Methods cannot have their own type parameters yet.",
		"Array index must be an integer.",
		"Value has no length.",
		"Array index is out of range.",
		"Dereferencing null.",
		"Shift amount is out of range.",
		"Literal does not fit in the target type.",
		"Function might end without returning a value.",
	};
	inline const char* g_DiagnosticAdvices[] = {
		"The issue occurred at {}. Please report this if unexpected.",
		"‘{}’ is not recognized as valid syntax. Check for typos or missing characters.",
		"Ensure the denominator is not zero before performing division.",
		"‘{}’ is not a valid operator in this context. Check the operator or operand types.",
		"Make sure every ‘/*’ has a matching ‘*/’. Comment started near {}.",
		"A string literal starting at ‘{}’ was not closed. Ensure all strings end with a quote.",
		"The file ended prematurely. Check for unclosed brackets, comments, or incomplete statements.",
		"‘{}’ is not a valid number. Ensure correct syntax for integers and decimals.",
		"A character literal starting at ‘{}’ is not valid. Ensure only one character long.",
		"‘{}’ was already defined in this scope. Rename or remove the duplicate declaration.",
		"‘{}’ is not defined in the current scope. Check for typos or missing declarations.",
		"Cannot assign or operate on incompatible types like ‘{}’. Check for implicit casts or incorrect types.",
		"‘{}’ is not a recognized escape sequence. Use sequences like \\n, \\t, \".",
		"There is an unmatched ‘{}’.",
		"‘{}’ was not expected here. Check for a missing operator, bracket or line break.",
		"Add a colon ':' after {} to begin an indented code block",
		"Add a line break after ':' and indent the next line to start the block",
		"Add a valid name or identifier after {}",
		"Assign a value using '=' after the identifier to complete the statement",
		"Ensure 'else' is used directly after a valid 'if' or 'elif' block",
		"Write loops as 'for i in 0..n:', 'for i in 1..=n:' or 'for item in array:' (near ‘{}’)",
		"Add '(' to begin the function’s parameter list",
		"Close the function’s parameter list with ')'",
		"Separate each function parameter with a comma ','",
		"Add '->' followed by the return type after the parameter list",
		"Ensure all indented blocks are properly closed",
		"Write the file to import as a string, e.g. import \"math\" (near ‘{}’)",
		"Separate items with a comma ',' at {} to continue the list or argument sequence.",
		"Add a colon ':' after {} to start the block or specify the case body.",
		"Give ‘{}’ a type (let x: int) or a value to infer it from (let x = 0).",
		"‘{}’ can only appear inside a while or for loop.",
		"Move ‘...’ to the end of the parameter list.",
		"‘{}’ was not found relative to the importing file. Check the path and that it is part of the build.",
		"Use a literal or constant expression greater than zero for the size near ‘{}’.",
		"Only a name can follow ‘.’, near ‘{}’.",
		"‘{}’ is not a field or method of this type. Check the spelling or the class definition.",
		"Define __getitem__ (and __setitem__ for assignment) on the class to support ‘[]’ near ‘{}’.",
		"‘{}’ is not a type. Use a built-in type like int or float64, a class name, or a pointer such as *int.",
		"‘{}’ is not supported. Convert one side with ‘as’ if a conversion is intended.",
		"The value near ‘{}’ cannot be converted to the declared return type.",
		"Add a value after ‘{}’ that matches the function's return type.",
		"‘{}.",
		"The argument near ‘{}’ cannot be converted implicitly. Use ‘as’ to convert explicitly.",
		"‘{}’ is not a function or method.",
		"The left side near ‘{}’ must be a variable, field, dereferenced pointer or index.",
		"The value ‘{}’ already appears in an earlier case.",
		"‘{}’ is not a compile-time integer constant.",
		"Write the type arguments explicitly, for example ‘{}[int]’.",
		"Converting ‘{}’ needs an explicit cast, for example ‘value as T’.",
		"A for loop needs a range (0..n) or a fixed size array, ‘{}’ is neither.",
		"Each branch of a switch starts with ‘case value:’ or ‘default:’, found ‘{}’.",
		"Give ‘{}’ a value: const name = value.",
		"‘{}’ was declared with const. Use let if it needs to change.",
		"The value of ‘{}’ must be known at compile time.",
		"Move ‘{}’ into a function body.",
		"‘{}’ cannot be switched on. Use if/elseif for other types.",
		"‘{}’. Define the dunder method on the class to support the operator.",
		"‘{}’ must take exactly two parameters: self and the other operand.",
		"‘{}.",
		"Make ‘{}’ a generic function outside the class, or make the class itself generic.",
		"‘{}’). Use ‘as’ to convert the index to an integer type.",
		"len() works on arrays, str and classes with __len__, not ‘{}’.",
		"‘{}).",
		"‘{}’ never points at a value, so it cannot be dereferenced.",
		"Shifting by ‘{}).",
		"‘{}’. Use a wider type or an explicit ‘as’ if wrapping is intended.",
		"Every path through ‘{}’ must end with a return statement.",
	};
}
