[None]
Message = "An unknown error has occurred."
Advice  = "The issue occurred at {}. Please report this if unexpected."

[InvalidSyntax]
Message = "Syntax error: unexpected or invalid token."
Advice  = "‘{}’ is not recognized as valid syntax. Check for typos or missing characters."

[DivisionByZero]  
Message = "Division by zero is undefined."
Advice  = "Ensure the denominator is not zero before performing division."

[InvalidOperator]
Message = "Invalid or unsupported operator used."
Advice  = "‘{}’ is not a valid operator in this context. Check the operator or operand types."
