// Documentation for what the language itself provides: keywords, built-in types and functions.

export interface BuiltinFunction {
    name: string;
    signature: string;
    params: string[];
    doc: string;
}

export const BUILTIN_FUNCTIONS: BuiltinFunction[] = [
    { name: "print", signature: "print(values...)", params: ["values..."], doc: "Prints the values separated by spaces, then a newline. Classes print with `operator str`, or as `Name(field=value, ...)`." },
    { name: "len", signature: "len(value) -> int64", params: ["value"], doc: "The number of items in an array, slice, `str`, `String`, `List`, `Map`, or any class with `operator len`." },
    { name: "hash", signature: "hash(value) -> uint64", params: ["value"], doc: "A hash of the value: numbers, `str`, `String`, enums, pointers, or a class with `operator hash`." },
    { name: "sizeof", signature: "sizeof(T) -> int64", params: ["T"], doc: "The size of a type in bytes." },
    { name: "view", signature: "view(pointer: *T, count: int64) -> []T", params: ["pointer: *T", "count: int64"], doc: "A slice that looks at `count` items starting at `pointer`. Nothing is copied." },
    { name: "free", signature: "free(pointer)", params: ["pointer"], doc: "Gives memory back early. The automatic cleanup afterwards does nothing." },
    { name: "destroy", signature: "destroy(pointer: *T)", params: ["pointer: *T"], doc: "Cleans up `*pointer` (runs its `operator destruct`). For code that manages raw memory itself, like `List`." },
    { name: "take", signature: "take(pointer: *T) -> T", params: ["pointer: *T"], doc: "Hands the value at `pointer` out of raw memory without copying it." },
    { name: "clone", signature: "clone(pointer: *T) -> T", params: ["pointer: *T"], doc: "A copy of the value at `pointer` (with `operator copy` if the type has one)." },
    { name: "pause", signature: "pause()", params: [], doc: "Inside an `async function`: `await pause()` gives other tasks a turn." },
];

export const PRIMITIVE_DOCS: Record<string, string> = {
    bool: "`true` or `false`.",
    int: "A 32-bit signed integer (same as `int32`). Integer literals are `int` unless the declared type says otherwise.",
    int8: "An 8-bit signed integer. `*int8` is a C `char*`.",
    int16: "A 16-bit signed integer.",
    int32: "A 32-bit signed integer.",
    int64: "A 64-bit signed integer. `len()` returns this.",
    uint: "A 32-bit unsigned integer (same as `uint32`).",
    uint8: "An 8-bit unsigned integer (a byte).",
    uint16: "A 16-bit unsigned integer.",
    uint32: "A 32-bit unsigned integer.",
    uint64: "A 64-bit unsigned integer.",
    float: "A 64-bit float (same as `float64`).",
    float32: "A 32-bit float.",
    float64: "A 64-bit float. Literals like `2.5` are `float64`.",
    str: "Text you look at: a pointer and a length. Free to make and pass around; `s[a:b]` views part of it without copying. Use `String` to own and change text.",
    String: "Text you own: on the heap, growable, cleaned up at the end of its scope. Always available (no import needed).",
    List: "`List[T]`: a growable array. Available as soon as a file uses it. `push`, `pop`, `last`, `contains`, `map`, `filter`, `sort`, `sort_by`...",
    Map: "`Map[K, V]`: a hash map. Available as soon as a file uses it. `m[k] = v`, `get` (-> `?V`), `get_or`, `in`, `remove`, `len`, `for key in m`.",
    Generator: "`Generator[T]`: what a function with `yield` returns. Loop over it with `for`, or step by hand with `advance()`, `value()`, `done()`.",
    Task: "`Task[T]`: what an `async function` returns. `run()` runs it to the end; `await` it inside another async function.",
};

export const KEYWORD_DOCS: Record<string, string> = {
    let: "Declares a variable: `let x = 1`, `let x: int64 = 1`, `let a, b = pair()`.",
    const: "A compile-time constant: `const LIMIT = 4`.",
    function: "Declares a function: `function name(a: int, b: int = 0) -> int:`. Also the type of function values: `function(int) -> int`.",
    async: "`async function` returns a `Task[T]` that runs when something resumes it: `task.run()`, or `await task` in another async function.",
    await: "Inside an `async function`: runs another task, pausing whenever it pauses, and gives its result.",
    yield: "Inside a function that returns `Generator[T]`: hands out the next value and pauses until the loop asks for another.",
    operator: "A method that gives your class an operator: `add subtract multiply divide modulo power equals not_equals less less_equal greater greater_equal get set len iterate contains call str hash slice destruct copy`.",
    property: "A getter `property name(self) -> T:` used as `obj.name`, or a setter `property name(self, value: T):` used as `obj.name = v`.",
    class: "Declares a class: fields (`name: type = default`), methods, operators. `class Dog(Animal, Trait):` inherits from one base class and lists traits.",
    trait: "A set of methods a class must have, checked at compile time: `function report[T: Shape](s: *T)`.",
    enum: "An enum; cases can carry data: `Circle(radius: float64)`. A `switch` over it must cover every case.",
    variant: "Holds a value of one of its types and remembers which: read with `as`, test with `is`, or `switch ... case int(i):`.",
    union: "Fields that share memory. Prefer `variant`, which knows what it holds.",
    macro: "`macro name(args):` pastes its body where it is used as `name!(...)`. Variables it declares get private names.",
    declare: "Declares a C function so Clear can call it: `declare printf(format: *int8, args: ...) -> int32`.",
    import: "`import \"math\"` (standard library), `import \"lib/geometry\"` (a file, `.cl` implied), `import \"colors\"` (a package), `import \"x\" as y` (use as `y.name`).",
    as: "Converts: `big as int32`, `n as float64` (for a variant: checked). In imports: `import \"x\" as y`.",
    is: "Tests a variant, enum case or optional: `n is float64`, `s is Shape.Rect`, `found is none`, `found is not none`.",
    in: "`for x in values:`, and the membership test `x in values` / `x not in values`.",
    when: "The conditional expression: `when condition use a otherwise b`.",
    use: "Part of `when condition use a otherwise b`.",
    otherwise: "Part of `when condition use a otherwise b`.",
    if: "`if condition:` / `else if` / `else:`. `if x := maybe():` declares and tests an optional.",
    else: "`else:` or `else if condition:`.",
    elseif: "Same as `else if`.",
    while: "`while condition:`. `while line := read_line():` loops while an optional holds a value.",
    for: "`for i in 0..5:` (0 to 4), `for i in 1..=3:`, `for item in list:` (objects are visited in place), `for k, v in pairs:`.",
    switch: "`switch value:` with `case 1, 2:`, `case Circle(r):`, `case some(x):`, `case int(i):`, `default:`. No fallthrough.",
    case: "A branch of a `switch`. Can unpack data: `case Rect(w, h):`.",
    default: "The `switch` branch for everything else.",
    return: "Returns from the function. `return a, b` returns a tuple.",
    break: "Leaves the innermost loop.",
    continue: "Goes to the next iteration of the innermost loop.",
    pass: "Does nothing; fills an empty block.",
    defer: "Runs a statement when the enclosing block exits, however it exits.",
    assert: "`assert condition, \"message\"` stops the program with the message when the condition is false.",
    lambda: "A function value: `lambda x: x + 1`, `lambda (x: int): x * 2`. `move lambda` moves captured values in.",
    move: "`move lambda` moves the values it uses into the lambda instead of borrowing them.",
    and: "Logical and (short-circuit).",
    or: "Logical or (short-circuit).",
    not: "Logical not; also `not in` and `is not`.",
    true: "The `bool` true.",
    false: "The `bool` false.",
    none: "The empty value of an optional `?T`.",
    null: "The null pointer.",
    self: "The object a method was called on (a pointer to it).",
    super: "`super.method()` calls the base class's version.",
    sizeof: "`sizeof(T)`: the size of a type in bytes.",
};
